routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('site.index');
});

Route::get('/sobre-nos', function () {
    return view('site.sobre-nos');
});

Route::get('/pesquisas-genealogicas', function () {
    return view('site.pesquisa-genealogica');
});

Route::get('/busca-de-documentos', function () {
    return view('site.buscadocumentos');
});

// Busca de documentos Integra
    Route::get('/busca-de-documentos/brasil', function () {
        return view('site.buscadocumentos-integra');
    });

    Route::get('/busca-de-documentos/espanha', function () {
        return view('site.buscadocumentos-integra');
    });

    Route::get('/busca-de-documentos/italia', function () {
        return view('site.buscadocumentos-integra');
    });

    Route::get('/busca-de-documentos/alemanha-austria-polonia', function () {
        return view('site.buscadocumentos-integra');
    });

    Route::get('/busca-de-documentos/portugal', function () {
        return view('site.buscadocumentos-integra');
    });

    Route::get('/busca-de-documentos/demais-certidoes', function () {
        return view('site.buscadocumentos-integra');
    });


Route::get('/fale-conosco', function () {
    return view('site.contato');
});

Route::post('fale-conosco', 'ContatoController@sendEmail')->name('contato');

// Route::get('/blog', function () {
//     return view('site.blog-listagem');
// });

// Route::get('/blog/integra', function () {
//     return view('site.blog-integra');
// });

// Blog ==============================================================================
Route::group(['prefix' => 'blog'], function () {
    Route::get('/', 'BlogController@index')->name('site.blog.blog');

    Route::get('/{name}', 'BlogController@show')->name('site.blog.integra');
});

// Paginas de Erros

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Corcel\Model\Post as Corcel;

class Post extends Corcel
{
    protected $connection = 'wordpress';

    public function index(){}

    public function getPostDateAttribute($value)
    {
        return date('d/m/Y', strtotime($value));
    }

    public function getPostContentAttribute($value)
    {
        $stringWithBRs = nl2br($value);
        $stringWithPs = str_replace("<br /><br />", "</p>\n<p>", $stringWithBRs);
        $stringWithPs = "<p>" . $stringWithPs . "</p>";
        return $stringWithPs;
    }

    public function getMetasAttribute()
    {
        $metas = [];
        foreach ($this->meta as $meta) {
            $metas[$meta->meta_key] = $meta->value;
        }
        return $metas;
    }

    public function getSeoAttribute()
    {
        $metas = $this->metas;

        return [
            'keywords' => !empty($metas['_yoast_wpseo_focuskw']) ? $metas['_yoast_wpseo_focuskw'] : '',
            'title' => !empty($metas['_yoast_wpseo_title']) ? $metas['_yoast_wpseo_title'] : '',
            'description' => !empty($metas['_yoast_wpseo_metadesc']) ? $metas['_yoast_wpseo_metadesc'] : '',
            'metakeywords' => !empty($metas['_yoast_wpseo_metakeywords']) ? $metas['_yoast_wpseo_metakeywords'] : '',
            'noindex' => !empty($metas['_yoast_wpseo_meta-robots-noindex']) ? $metas['_yoast_wpseo_meta-robots-noindex'] : '',
            'nofollow' => !empty($metas['_yoast_wpseo_meta-robots-nofollow']) ? $metas['_yoast_wpseo_meta-robots-nofollow'] : '',
            'opengraph-title' => !empty($metas['_yoast_wpseo_opengraph-title']) ? $metas['_yoast_wpseo_opengraph-title'] : '',
            'opengraph-description' => !empty($metas['_yoast_wpseo_opengraph-description']) ? $metas['_yoast_wpseo_opengraph-description'] : '',
            'image' => !empty($metas['_yoast_wpseo_opengraph-image']) ? $metas['_yoast_wpseo_opengraph-image'] : '',
            'twitter-title' => !empty($metas['_yoast_wpseo_twitter-title']) ? $metas['_yoast_wpseo_twitter-title'] : '',
            'twitter-description' => !empty($metas['_yoast_wpseo_twitter-description']) ? $metas['_yoast_wpseo_twitter-description'] : '',
            'twitter-image' => !empty($metas['_yoast_wpseo_twitter-image']) ? $metas['_yoast_wpseo_twitter-image'] : '',
        ];
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\Post;
use App\Http\Controllers\Controller;

class BlogController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->get('search');

        if($search){
            $posts = Post::published()
                ->search($search)
                ->whereIn('post_type', ['post'])
                ->newest()->paginate(4);
        }else{
            $posts = Post::published()
                ->whereIn('post_type', ['post'])
                ->newest()->paginate(4);
        }
        
        return view('site.blog.blog', ['posts' => $posts]);
    }



    public function show($name)
    {
        $post = Post::slug($name)->with('attachment')->first();
        if(!$post){
            return view('site.blog.404');
        }
        $post->meta_description = strip_tags($post->content);
        $post->meta_description = Str::limit(trim($post->meta_description), 120);
        
        
        $other_posts = Post::published()
                        ->newest()->limit(2)
                        ->whereIn('post_type', ['post'])
                        ->where('id', '<>', $post->ID)->get();
        return view('site.blog.integra', ['post' => $post, 'other_posts' => $other_posts]);
    }
}

app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SendEmailContato;
use App\Http\Requests\SendContatoRequest;
use Illuminate\Http\Request;
use Mail;
Use Exception;

class ContatoController extends Controller
{
    public function sendEmail(SendContatoRequest $req)
    {
        $data = [
            'nome' => $req->nome_contato,
            'email' => $req->email_contato,
            'telefone' => $req->telefone_contato,
            'mensagem' => nl2br($req->mensagem_contato)
        ];

        try {
            Mail::to(env('MAIL_ADDRESS_TO', $data['email']))->send(new SendEmailContato($data));
            return redirect()->back()->with('success', 'Dados enviados com sucesso!');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Não foi possível enviar a mensagem!');
        }
        return;

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/site/blog/404.blade.php
@extends('site.layout.main')

@section('title', 'Blog')
@section('meta-desc', 'Blog Docforce')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/blog') }}">@yield('title')</a>
</li>
@endsection

@section('content')

<div class="row blog page" id="Blog">
	<div class="container-fluid bg-gray-blog">
		<div class="container">
			<div class="row page-title">
				<div class="container">
					@include('site.includes.breadcrumb')
				</div>
			</div>
		</div>
	</div>

	<div class="container blog">
		<div class="row pb-5">
			<div class="col-sm-12 col-md-12 col-lg-8">
                <div class="conteudo">
					<h3 class="title-blog">
                        Blog<br>
						<strong>Dicas e Notícias</strong>
					</h3>
				</div>
            </div>

            <div class="col-sm-12 col-md-12 col-lg-4">
                @include('site.blog.includes.searchbox')
            </div>

            <div class="container listagem-posts">


					<div class="container blog-404">
						<div class="row justify-content-center">
							<p class="h1">Essa página não existe!</h1>
								<br>
								<br>
								<br>
						</div>
						<div class="row justify-content-center">
							<div class="btn-area">
								<a href="{{url('/blog')}}" class="btn btn-default">Clique aqui para retornar ao Blog</a>
							</div>
						</div>
					</div>
				
            </div>
		</div>
	</div>
</div>


@include('site.includes.cta-faleconosco')

@endsection

resources/views/site/blog/blog.blade.php
@extends('site.layout.main')

@section('title', 'Blog')
@section('meta-desc', 'Blog Docforce')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/blog') }}">@yield('title')</a>
</li>
@endsection

@section('content')

<div class="row blog page" id="Blog">
	<div class="container-fluid bg-gray-blog">
		<div class="container">
			<div class="row page-title">
				<div class="container">
					@include('site.includes.breadcrumb')
				</div>
			</div>
		</div>
	</div>

	<div class="container blog">
		<div class="row pb-5">
			<div class="col-sm-12 col-md-12 col-lg-8">
                <div class="conteudo">
					<h3 class="title-blog">
                        Blog<br>
						<strong>Dicas e Notícias</strong>
					</h3>
				</div>
            </div>

            <div class="col-sm-12 col-md-12 col-lg-4">
                @include('site.blog.includes.searchbox')
            </div>

            <div class="container listagem-posts">

                @if($posts->isNotEmpty())
                    @include('site.blog.includes.list', ['posts' => $posts])
					{!! $posts->links('site.includes.pagination') !!}
				@else
					<div class="container">
						<div class="row justify-content-center">
							<p class="h1">Nenhum post encontrado.</h1>
						</div>
					</div>
					
				@endif
				
            </div>
		</div>
	</div>
</div>


@include('site.includes.cta-faleconosco')

@endsection

resources/views/site/blog/includes/list.blade.php
@if($posts->isNotEmpty())

    @foreach($posts as $post)
    <a href="{{ route('site.blog.integra', ['name' => $post->post_name]) }}">
    <div class="card">
        <div class="card-body">
            @if ($post->thumbnail !== null)
            <?php
                $thumbnail = $post->thumbnail->size('post-thumb-wide')
            ?>
            <div class="card-img">
            <img src="{{ $thumbnail }}" alt="{{ $post->title }}" class="img-fluid img">
            </div>
            @else
            <p class="d-flex align-items-center mx-auto">Imagem Indisponível</p>
            @endif


            <div class="card-content">
                <span class="card-date"><i class="far calendar fa-calendar-alt"></i>{{ $post->post_date }}</span>

                <h2 class="card-title">{{ $post->title }}</h2>
                
                <p class="card-text">
                    {{ strip_tags(substr($post->content, 0, 200))}}
                </p>

                
                <div class="btn-area">
                    <span class="btn btn-readmore"><i class="fas plus fa-plus"></i>Leia mais</span>
                </div>
            </div>
            
        </div>
    </div>
    </a>
    @endforeach
 
@endif

resources/views/site/blog/includes/other-post.blade.php
@if($posts->isNotEmpty())

    @foreach($posts as $post)
    
    <a href="{{ route('site.blog.integra', ['name' => $post->post_name]) }}">
        <div class="post">
            <div class="card">
                @if ($post->thumbnail !== null)
                <?php
                    $thumbnail = $post->thumbnail->size('post-thumb-wide')
                ?>
                <img src="{{ $thumbnail }}" alt="{{ $post->title}}" class="card-img-top">
                @else

                @endif
                <div class="card-body">
                    <p class="card-text">{{ $post->title }}</p>
                </div>
                <div class="btn-area">
                    <span class="btn btn-readmore"><i class="fas plus fa-plus"></i>Leia mais</span>
                </div>
                </div>
        </div>
    </a>

    @endforeach

@endif

resources/views/site/blog/includes/searchbox.blade.php
<form action="/blog" type="GET">
    <span class="search-box"> 
        <input type="text" name="search" class="search-input" placeholder="Buscar" value="{{ (isset($_GET['search']) && !empty($_GET['search']))? $_GET['search'] : '' }}" required="required" tabindex="1">
        <button type="submit" class="search-icon" tabindex="2"><i class="fa fa-search"></i></button>
    </span>
</form>

resources/views/site/blog/integra.blade.php
@extends('site.layout.main')

@section('title', 'Blog')
@section('meta-desc', 'Blog Docforce')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/blog') }}">Blog</a>
</li>
@endsection

@section('content')



<div class="row blog page" id="Blog">
	<div class="container-fluid bg-gray-blog">
		<div class="container">
			<div class="row page-title">
				<div class="container">
					@include('site.includes.breadcrumb')
				</div>
			</div>
		</div>
	</div>

	<div class="container blog">
		<div class="row pb-5 integra">
			<div class="col-sm-12 col-md-12 col-lg-12">
                <div class="conteudo">
					<h3 class="title-post">
                        <span class="card-date"><i class="far calendar fa-calendar-alt"></i>{{ $post->post_date }}</span>
						<strong>{{ $post->title }}</strong>
					</h3>
				</div>
            </div>

            <div class="container row post-integra">
                <div class="col-sm-12 col-lg-8">
                    <div class="post">
                        <div class="post-body">

                            @if($post->thumbnail !== null)
                            <?php
                                $thumbnail = $post->thumbnail->size('post-featured');
                                $thumbnail = (is_array($thumbnail))? $thumbnail = $thumbnail['url'] : $thumbnail;
                            ?>
                            <img src="{{ $thumbnail }}" alt="{{ $post->title }}" class="img-fluid">
                            @else
                                <p class="d-flex h-50 align-items-center mx-auto">Imagem Indisponível</p>
                            @endif

                            <div class="post-content">
                                <p class="post-text">
                                    {{ strip_tags($post->post_content)}}
                                </p>
                            </div>

                            <div class="share-post">
                                <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhar</a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-12 col-lg-3 offset-1 other-posts">
                    <div class="title">
                        <i class="far icon fa-file-alt"></i>
                        <span>Outras Notícias</span>
                    </div>

                    @include('site.blog.includes.other-post', ['posts' => $other_posts])

                </div>

            </div>
		</div>
	</div>
</div>
		
@include('site.includes.cta-faleconosco')

@endsection

resources/views/site/buscadocumentos-integra.blade.php
@extends('site.layout.main')

@section('meta-desc', 'Saiba mais sobre a Docforce.')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/busca-de-documentos') }}">@yield('title')</a>
</li>
@endsection

@section('content')

@if(Request::segment(2) == 'brasil')
	@section('title', 'Busca de Certidões no Brasil')
	@include('site.includes.documentos.certidao-brasil')
@endif

@if(Request::segment(2) == 'espanha')
	@section('title', 'Busca de Certidões na Espanha')
	@include('site.includes.documentos.certidao-espanha')
@endif

@if(Request::segment(2) == 'italia')
	@section('title', 'Busca de Certidões na Itália')
	@include('site.includes.documentos.certidao-italia')
@endif

@if(Request::segment(2) == 'alemanha-austria-polonia')
	@section('title', 'Busca de Certidões na Alemanha, Áustria e Polônia')
	@include('site.includes.documentos.certidao-alemanha')
@endif


@if(Request::segment(2) == 'portugal')
	@section('title', 'Busca de Certidões em Portugal')
	@include('site.includes.documentos.certidao-portugal')
@endif

@if(Request::segment(2) == 'demais-certidoes')
	@section('title', 'Demais Buscas de Certidões')
	@include('site.includes.documentos.demais-certidoes')
@endif


@include('site.includes.cta-faleconosco')

@endsection

@section('js')
<script type="text/javascript">
	// start.plugins.swiper.sliderBrands();
</script>
@endsection

resources/views/site/buscadocumentos.blade.php
@extends('site.layout.main')

@section('title', 'Busca de Documentos')
@section('meta-desc', 'Busca de documentos')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/busca-de-documentos') }}">@yield('title')</a>
</li>
@endsection

@section('content')

<div class="row produtos page bg-about" id="Certidoes">
	<div class="container">
		<div class="row page-title">
			<div class="container">
				@include('site.includes.breadcrumb')
			</div>
		</div>

		<div class="row-fluid certidoes">
			<h3 class="title">
				<strong>Certidão por Países</strong>
			</h3>
		</div>

		<div class="row certidoes-list">

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/brasil')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title brazil">Busca de Certidões<br>no Brasil</h3>
							<p class="description">
								As certidões e registros históricos no Brasil dos seus antepassados, que não estão no acervo da família, podem ser recuperadas com nossa equipe.
								{{-- A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa. --}}
							</p>
							<div class="btn-area">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/espanha')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title spain">Busca de Certidões<br>na Espanha</h3>
							<p class="description">
								Devido a imigração europeia que ocorreu entre os séculos XIX e XX, estima-se que aproximadamente 15 milhões de brasileiros tenham descendência espanhola.
								{{-- A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa. --}}
							</p>
							<div class="btn-area">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/italia')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title italy">Busca de Certidões<br>na Itália</h3>
							<p class="description">
								A Itália é um dos países mais procurados pelos brasileiros para o reconhecimento da dupla cidadania.
								{{-- A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa. --}}
							</p>
							<div class="btn-area d-block mt-auto">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/alemanha-austria-polonia')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title global">Busca de Certidões<br>na Alemanha, Austria e Polônia</h3>
							<p class="description">
								Os Brasil recebeu um grande número de imigrantes dos países germânicos durante o século XIX e XX. A maioria se estabeleceu, criando famílias e dando a origem a diversos descentes no nosso país.
								{{-- A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa. --}}
							</p>
							<div class="btn-area">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/portugal')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title portugal">Busca de Certidões<br>em Portugal</h3>
							<p class="description">
								Brasileiros descendentes de portugueses podem solicitar a atribuição de cidadania sanguínea para sua família.
								{{-- A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa. --}}
							</p>
							<div class="btn-area">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

			<div class="col-sm-12 col-md-6 no-pad">
				<a href="{{url('/busca-de-documentos/demais-certidoes')}}">
					<div class="card box">
						<div class="content">
							<h3 class="title other">Demais Buscas de<br>Certidões</h3>
							<p class="description">
								A docforce realiza a busca por documentos<br>
								históricos em outros países e os entrega na sua<br>casa.
							</p>
							<div class="btn-area d-block mt-auto">
								<span class="btn btn-certidao">Saiba mais</span>
							</div>
						</div>
					</div>
				</a>
			</div>

		</div>

		

		{{-- @include('site.includes.pagination') --}}
	</div>
</div>

@include('site.includes.cta-faleconosco')

@endsection

resources/views/site/contato.blade.php
@extends('site.layout.main')

@section('title', 'Fale Conosco')
@section('meta-desc', 'Entre em Contato em caso de dúvidas, solicitações ou sugestões.')

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
	<a href="{{ url('/fale-conosco') }}">@yield('title')</a>
</li>
@endsection

@section('content')

<div class="row contato page" id="contato">
	<div class="container-fluid bg-gray">
		<div class="container">
			<div class="row page-title">
				<div class="container">
					@include('site.includes.breadcrumb')
				</div>
			</div>

			<div class="row content">
				<div class="container">

					<div class="row">
						<div class="col-12 title-area">
							<h1 class="title">
								Contato<br>
								<strong>Fale Conosco</strong>
							</h1>
							<h3 class="subtitle">
								Em caso de dúvidas, solicitações ou sugestões, entre em contato conosco!<br>
								Nosso telefone é <a href="tel:+5511941565963"><b>(11) 94156-5963</b></a> ou se preferir, preencha o formulário abaixo.
							</h3>
						</div>


						<div class="col-lg-8">
                            <form action="{{ route('contato') }}" method="POST" class="form" id="formContato">
                                @csrf

                                @if(session('error'))
                                    <div class="col-11 col-lg-12 alert alert-danger" role="alert">
                                        {{session('error')}}
                                    </div>
                                @endif

                                @if(session('success'))
                                    <div class="box-lightgreen" id="">
                                        <span class="send">{{session('success')}}</span>
                                    </div>
                                @endif

								<div class="form-group">
									<label class="title-input" for="nome_contato">*Nome:</label>
                                    <input type="text" value="" name="nome_contato" id="nome_contato" class="form-control" required="required" />
                                    @if ($errors->has('nome_contato'))
                                        <small class="text-danger" role="alert">
                                            <strong>{{ $errors->first('nome_contato') }}</strong>
                                        </small>
                                    @endif
								</div>

								<div class="form-row">
									<div class="form-group col-12 col-sm-7">
										<label class="title-input" for="email_contato">*E-mail:</label>
                                        <input type="email" value="" name="email_contato" id="email_contato" class="form-control" required="required" placeholder="Ex: mail@exemplo.com.br" />
                                        @if ($errors->has('email_contato'))
                                            <small class="text-danger" role="alert">
                                                <strong>{{ $errors->first('email_contato') }}</strong>
                                            </small>
                                        @endif
									</div>

									<div class="form-group col-12 col-sm-5">
										<label class="title-input" for="telefone_contato">*Telefone:</label>
                                        <input type="text" value="" name="telefone_contato" id="telefone_contato" class="form-control telephone" required="required" placeholder="EX: (00)0000-0000" >
                                        @if ($errors->has('telefone_contato'))
                                            <small class="text-danger" role="alert">
                                                <strong>{{ $errors->first('telefone_contato') }}</strong>
                                            </small>
                                        @endif
									</div>
								</div>

								<div class="form-group">
									<label class="title-input" for="mensagem_contato">*Mensagem:</label>
                                    <textarea name="mensagem_contato" maxlength="480" id="mensagem_contato" cols="30" rows="5" class="form-control" required="required" placeholder="Digite aqui a mensagem que deseja nos passar"></textarea>
                                    @if ($errors->has('mensagem_contato'))
                                        <small class="text-danger" role="alert">
                                            <strong>{{ $errors->first('mensagem_contato') }}</strong>
                                        </small>
                                    @endif
								</div>

								<div class="form-group btns">
									<button type="submit" class="btn btn-default btn-enviar">Enviar Mensagem</button>
								</div>
							</form>
						</div>

						<div class="col-lg-4 contacts">
							<ul class="contact-list">
								<li class="contact telephone">
									<div class="circle">
										<i class="fas fa-phone icon"></i>
									</div>
									<p class="contact-description">
										<b>Contato</b>
										{{-- <br>
										<span class="text-decoration: none!important;">(13) 0000-0000</span> --}}

									</p>
									{{-- Telefone aqui está no after via css --}}
									<a style="text-decoration: none;" href="tel:+5511941565963" target="_blank" title="Entre em contato conosco por telefone"></a>
								</li>

								{{-- <li class="contact whatsapp">
									<div class="circle">
										<i class="fab fa-whatsapp icon"></i>
									</div>
									<p class="contact-description">
										<b>Whatsapp</b><br />
										{{ ('number_formated') }}
									</p>
									<a href="{{ ('url') }}" target="_blank" class="whatsapplink" title="Envie-nos uma mensagem por Whatsapp"></a>
								</li> --}}

								<li class="contact email">
									<div class="circle">
										<i class="far fa-envelope icon"></i>
									</div>
									<p class="contact-description">
										<b>E-mail</b><br />
										contato.docforce@gmail.com
									</p>
									<a href="mailto:contato.docforce@gmail.com" target="_blank" title="Entre em contato conosco por e-mail"></a>
								</li>

								{{-- <li class="contact atendimento">
									<div class="circle">
										<i class="far fa-clock icon"></i>
									</div>
									<p class="contact-description">
										<b>Atendimento</b><br />
										Segunda à Sexta-feira: das 8 às 18hrs
									</p>
								</li> --}}

								{{-- <li class="contact localizacao">
									<div class="circle">
										<i class="fas fa-map-marker-alt icon"></i>
									</div>
									<p class="contact-description">
										<b>Localização</b><br />
										Av. Senador Feijó, 686<br />
										Vila Matias, Santos - SP
									</p>
									<a href="https://goo.gl/maps/stNPM318DPp8ECvU9" target="_blank" title="Clique para visualizar nosso endereço no Google Maps"></a>
								</li> --}}
							</ul>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

@include('site.includes.cta-faleconosco')

@endsection

@section('js')
{{--  --}}
@endsection

resources/views/site/includes/breadcrumb.blade.php
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item">Você está em</li>
		<li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
		@yield('breadcrumb')
	</ol>
</nav>